# Audits dependencies with cargo-deny
name: deps

permissions:
  contents: read

on:
  pull_request:
    paths:
      - Cargo.lock
      - deny.toml
      - .github/workflows/deps.yml

env:
  CARGO_INCREMENTAL: 0
  CARGO_NET_RETRY: 10
  RUST_BACKTRACE: short
  RUSTUP_MAX_RETRIES: 10

jobs:
  # Check for security advisories.
  #
  # Failures are not fatal, since issues are opened in the linkerd2 repo via rustsecbot.
  advisories:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
    - uses: actions/checkout@dcd71f646680f2efd8db4afa5ad64fdcba30e748
    - uses: EmbarkStudios/cargo-deny-action@9b350011b9d68c51a7ad7c2e7ec04bcc15dd0644
      with:
        command: check advisories

  # Audit licenses, unreleased crates, and unexpected duplicate versions.
  bans:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@dcd71f646680f2efd8db4afa5ad64fdcba30e748
    - uses: EmbarkStudios/cargo-deny-action@9b350011b9d68c51a7ad7c2e7ec04bcc15dd0644
      with:
        command: check bans licenses sources
