name: release

on:
  pull_request:
    paths:
      - .github/workflows/release.yml
      - action.yml
      - Cargo.toml
  push:
    tags:
      - 'release/*'

permissions:
  contents: write

env:
  CARGO_INCREMENTAL: 0
  CARGO_NET_RETRY: 10
  RUST_BACKTRACE: short
  RUSTUP_MAX_RETRIES: 10

jobs:
  publish:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    container:
      image: docker://rust:1.60-bullseye
    steps:
      - name: parse tag
        id: parse-tag
        run: |
          ref="${{ github.ref }}"
          if [[ "$ref" = refs/tags/release/* ]]; then
            v="${ref#refs/tags/release/}"
          else
            v=""
          fi
          echo "::set-output name=version::$v"
      - run: echo "version=${{ steps.parse-tag.outputs.version }}"

      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b

      - name: check crate version
        if: steps.parse-tag.outputs.version
        run: |
          apt update && apt install -y jq
          v=$(cargo metadata --frozen --format-version=1  | jq -r '.packages[] | select(.name == "cargo-action-fmt") | .version')
          echo "cargo.toml v$v"
          if [ "v${v}" != "${{ steps.parse-tag.outputs.version }}" ]; then
              echo "::error ::Crate version v${v} does not match tag version ${{ steps.parse-tag.outputs.version }}"
              exit 1
          fi

      - name: check action version
        if: steps.parse-tag.outputs.version
        run: |
          curl -Lo /usr/local/bin/yq https://github.com/mikefarah/yq/releases/download/v4.25.1/yq_linux_amd64
          chmod 755 /usr/local/bin/yq
          v=$(yq .inputs.version.default action.yml)
          echo "action.yml $v"
          if [ "v${v}" != "${{ steps.parse-tag.outputs.version }}" ]; then
              echo "::error ::Action version ${v} does not match tag version ${{ steps.parse-tag.outputs.version }}"
              exit 1
          fi

      - run: cargo fetch
      - name: cargo build
        run: |
          cargo build --release --frozen
          mv target/release/cargo-action-fmt target/cargo-action-fmt-x86_64-unknown-linux-gnu

      - run: cargo publish --dry-run

      - uses: softprops/action-gh-release@1e07f4398721186383de40550babbdf2b84acfc5
        if: steps.parse-tag.outputs.version
        with:
          name: ${{ steps.parse-tag.outputs.version }}
          files: target/cargo-action-fmt-x86_64-unknown-linux-gnu

      - if: steps.parse-tag.outputs.version
        run: cargo publish --token=${{ secrets.CRATESIO_TOKEN }}
