name: rustsec

on:

  # Run when the Cargo.lock changes or when this workflow changes.
  push:
    branches:
      - main
    paths:
      - Cargo.lock
      - deny.toml
      - .github/workflows/rustsec.yml

  # Run at 00:00 UTC every day
  schedule:
    - cron: '0 0 * * *'

permissions:
  issues: write

jobs:
  audit:
    runs-on: ubuntu-latest
    name: audit
    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8
      - uses: olix0r/rustsecbot@2d95b50b8ecabf23af6f4fd9ef5707630b8e916a
