name: rust-toolchain

on:
  pull_request:
    paths:
      - rust-toolchain
      - "**Dockerfile"
      - ".github/workflows/*"

permissions:
  contents: read

jobs:
  dev-action-images:
    runs-on: ubuntu-latest
    steps:
      - uses: linkerd/dev/actions/setup-tools@v36
      - uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633
      - run: just-dev check-action-images

  lint-actions:
    runs-on: ubuntu-latest
    steps:
      - uses: linkerd/dev/actions/setup-tools@v36
      - uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633
      - run: just-dev lint-actions
